"""法条表加联合唯一约束

Revision ID: 12eb65bb2964
Revises: bd5c6dde5900
Create Date: 2026-09-13 18:12:09.968040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12eb65bb2964'
down_revision: Union[str, Sequence[str], None] = 'bd5c6dde5900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_law_clause_version_id'), 'law_clause', ['version_id', 'clause_number'])
    op.create_unique_constraint(op.f('uq_law_version_version_name'), 'law_version', ['version_name', 'law_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_law_version_version_name'), 'law_version', type_='unique')
    op.drop_constraint(op.f('uq_law_clause_version_id'), 'law_clause', type_='unique')
    # ### end Alembic commands ###
