"""创建名字历史记录表

Revision ID: 6c98fa9fef3c
Revises: da8a6c71535f
Create Date: 2026-08-20 21:06:37.728498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c98fa9fef3c'
down_revision: Union[str, Sequence[str], None] = 'da8a6c71535f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('length', sa.String(length=10), nullable=False),
    sa.Column('other', sa.String(length=500), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_name_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_history')
    # ### end Alembic commands ###
