"""会话表 user_id 改非空并为消息表加可见结果列

Revision ID: 999e3a983165
Revises: 625710a381a7
Create Date: 2026-09-18 22:03:42.292713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '999e3a983165'
down_revision: Union[str, Sequence[str], None] = '625710a381a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('conversation_message', sa.Column('round_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_message', 'round_payload')
    op.alter_column('conversation', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
