"""新增禁用字样表与类别条款映射表

Revision ID: 9fa2079e211c
Revises: 12eb65bb2964
Create Date: 2026-09-14 19:01:15.548990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa2079e211c'
down_revision: Union[str, Sequence[str], None] = '12eb65bb2964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forbidden_word',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('word_kind', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forbidden_word')),
    sa.UniqueConstraint('word', 'word_kind', name=op.f('uq_forbidden_word_word'))
    )
    op.create_table('word_kind_clause',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_kind', sa.String(length=30), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['law_clause.id'], name=op.f('fk_word_kind_clause_clause_id_law_clause')),
    sa.ForeignKeyConstraint(['version_id'], ['law_version.id'], name=op.f('fk_word_kind_clause_version_id_law_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word_kind_clause')),
    sa.UniqueConstraint('version_id', 'word_kind', name=op.f('uq_word_kind_clause_version_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_kind_clause')
    op.drop_table('forbidden_word')
    # ### end Alembic commands ###
