"""新增法条版本表与条款表

Revision ID: bd5c6dde5900
Revises: e3c71357471c
Create Date: 2026-09-13 16:18:37.852414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5c6dde5900'
down_revision: Union[str, Sequence[str], None] = 'e3c71357471c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('law_name', sa.String(length=50), nullable=False),
    sa.Column('version_name', sa.String(length=30), nullable=False),
    sa.Column('enforcement_date', sa.DATE(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_law_version'))
    )
    op.create_table('law_clause',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('clause_number', sa.String(length=100), nullable=False),
    sa.Column('clause_original', sa.Text(), nullable=False),
    sa.Column('risk_grade', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['law_version.id'], name=op.f('fk_law_clause_version_id_law_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_law_clause'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_clause')
    op.drop_table('law_version')
    # ### end Alembic commands ###
