"""add poetry table

Revision ID: d3806561d24c
Revises: 6c98fa9fef3c
Create Date: 2026-08-24 23:48:49.285070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3806561d24c'
down_revision: Union[str, Sequence[str], None] = '6c98fa9fef3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('dynasty', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poetry')),
    sa.UniqueConstraint('source_id', 'source', name=op.f('uq_poetry_source_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poetry')
    # ### end Alembic commands ###
