"""创建名字收藏表

Revision ID: e3c71357471c
Revises: d3806561d24c
Create Date: 2026-08-29 22:48:36.051786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c71357471c'
down_revision: Union[str, Sequence[str], None] = 'd3806561d24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_favorite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('moral', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_name_favorite_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name_favorite'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_favorite')
    # ### end Alembic commands ###
