# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/auth/code?email=2489096039@qq.com

###
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "2489096039@qq.com",
  "username": "xihong",
  "password": "111111",
  "confirm_password": "111111",
  "code": "1327"
}

###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "2489096039@qq.com",
  "password": "111111"
}

###
POST http://127.0.0.1:8000/name/
Content-Type: application/json

{
  "surname": "王",
  "gender": "男",
  "length":"三字",
  "other": "要有王霸之气"
}